// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface StatbankBoxConfig {
  /**
   * Overstyr tittel
   */
  title?: string;

  /**
   * Overstyr lenke
   */
  href?: string;

  /**
   * Full bredde på boksen
   */
  fullWidthCheckBox: boolean;
}
