// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface EntryLinksConfig {
  /**
   * Inngang
   */
  entryLinks?: Array<{
    /**
     * Tittel
     */
    title: string;

    /**
     * URL
     */
    href: string;

    /**
     * Ikon
     */
    icon: string;

    /**
     * Mobil-Ikon
     */
    mobileIcon: string;
  }>;
}
